trigger:
  branches:
    include:
    - refs/heads/*

jobs:
- job: 'build_aks_demo'
  displayName: 'Build aks-demo'

  pool:
    vmImage: 'ubuntu-22.04'  
  
  steps:
  - checkout: self
    persistCredentials: true
    displayName: 'Checkout'

  - task: UseDotNet@2
    displayName: 'Install .NET 8'
    inputs:
      version: '8.x'

  - bash: |
      dotnet restore
    displayName: 'Run dotnet restore'

  - task: gitversion/setup@0
    displayName: 'Setup GitVersion'
    inputs:
      versionSpec: '5.x'
      includePrerelease: true

  - task: gitversion/execute@0
    displayName: Execute GitVersion
    inputs:
      useConfigFile: true
      configFilePath: 'GitVersion.yml'

  - task: Bash@3
    displayName: 'Set Version'
    inputs:
      targetType: 'inline'
      script: |
        echo 'Setting Build.BuildNumber to current version.'
        echo '##vso[build.updatebuildnumber]$(ImageVersion)'