trigger:
  branches:
    include:
    - refs/heads/*

jobs:
- job: 'build_aks_demo'
  displayName: 'Build aks-demo'
  pool:
    vmImage: 'ubuntu-22.04'  
  steps:
  - checkout: self
    persistCredentials: true
    displayName: 'Checkout'