apiVersion : apps/v1
kind: Deployment
metadata:
  name: aksdemo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksdemo
  template:
    metadata:
      labels:
        app: aksdemo 
    spec:
      containers:
        - name: aksdemo 
          image: crcebuaksdemo.azurecr.io/aksdemo
          ports:
          - containerPort: 80