nameOverride: ""
fullnameOverride: ""

replicaCount: 1
aspnetEnvironment: Production

image:
  repository: aks.demo:1.0.0-preview.48
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 30m
    nginx.ingress.kubernetes.io/client-body-buffer-size: 30m
    cert-manager.io/issuer: letsencrypt-http01-prod

  hosts:
    - host: aksdemo.cebuqueencity.com
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: letsencrypt-aks-demo-tls
     hosts:
       - aksdemo.cebuqueencity.com

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
